### ISSUE TITLE
keytree: commit Xpub first?

### ISSUE THREAD

**Issue by burdges** [stellar/slingshot#302]
I'm curious why Xpub gets committed to the transcript first before user supplied data in https://github.com/stellar/slingshot/blob/main/keytree/keytree.md  As a rule, accepting the user data first makes things more flexible, although it seems unimportant in this case.

**Comment by oleganza** [comment]
The idea is that PRF is _initialized_ with the Xpub and then _customized_ with the user's input as "derivation input". So that for each sibling key, the state of the PRF pre-customization is shared only among the immediate siblings, and not among some other keys (because it's bound to the parent xpub).

**Comment by burdges** [comment]
I see, but that's not a security reason since H(a, b) is equally unforgeable with control over a or b, given proper domain separation, etc.

I'd normally favor user data followed by protocol data with merlin transcripts, if only because user data may be complex and longer than 200 bytes, but it'll never matter here.
