### ISSUE TITLE
zkvm: disallow copying of Expressions and Constraints

### ISSUE THREAD

**Issue by oleganza** [stellar/slingshot#306]
For background, see a similar issue with programs: #301

The Constraint type represents a tree of Constraints that get flatten into a set of R1CS constraints when `verify` instruction is used. With the repeated use of `dup` and `and`/`or` instructions, it is conceivable to construct an exponentially large constraint tree with many multipliers and linear constraints, in a linearly growing program. Even if we can estimate the validation cost from the r1cs proof length, the proof could be invalid and we'd be still DoSed with just a horribly big transient R1CS instance before we even verify the proof. 

Options to deal with it:

1. Disallow copying of Constraints. Then, the CS cost is proportional to the length of the program. For the same reasons we should probably also disallow copying of Expressions.
2. Try to commit to number of linear constraints and multipliers upfront, and then check that we don't run out of them during program execution. This seems to be complicated and brittle.

**Comment by cathieyun** [comment]
Option 1 makes sense to me. After all, it doesn't make much sense to allow a user to copy a constraint... why would one want to copy a constraint, in order to impose the same constraint twice? In an outlier case where copying constraints makes sense, a user should probably just construct a new Constraint anyways.
