### ISSUE TITLE
zkvm:question: Spec Questions about payment channel example

### ISSUE THREAD

**Issue by XuyangSong** [stellar/slingshot#343]
https://github.com/stellar/slingshot/blob/main/zkvm/docs/zkvm-spec.md

I'm trying to comprehend and implement payment channel example in Spec Doc.
I hava a few questions:

1. “5.To prevent publication of a transaction using a stale authorization predicate
          ii  Any newer predicate can immediately spend that time-locked contract into a new “holding” contract with an updated distribution of funds.”

How to spend the “holding contract”?
What’s the predicate in “holding contract”? (I mean the in contested way)

2. What’s the difference between Program P1 and Predicate P1?  Is Program P1 one of PredicateTree branches in Predicate P1?

**Comment by oleganza** [comment]
Thanks for the interest in this. Unfortunately, the write up of this example is pretty outdated and rough. I'll try to put together a better description soon.

**Comment by SanJue** [comment]
Good Question! @song39567 
I'm confused about the payment channel too.

**Comment by dantengsky** [comment]
@oleganza Hi! 

Would you please help me to figure out the way that P2(of payment channel's construction) works.
 
> The final-distribution program P2:1. Checks that tx.mintime >= exptime (can be done via range:24(tx.mintime - exptime) which gives 6-month resolution for the expiration time) 2. Creates borrow/output combinations for each party with hard-coded predicate for each output. 3. Leaves the payload value and negatives from borrow on the stack to be consumed by the cloak instruction.

- Is P2 supposed to be executed by another program which unlocks the "holding contract" by using the `signtag` instruction?

- Is it necessary to add another constraint to P2, which checks if item `seq` of payload was as expected?  Otherwise, a valid (aggregated) signature of message (P2, seq) seems to be able to unlock any "holding contract".

Thanks!
